services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - ./.env
    depends_on:
      - llama3
    environment:
      - LLAMA3_API=http://llama3:${LLAMA3_PORT}
      - PORT=${BACKEND_PORT}
      - REPLICATE_API_KEY=${REPLICATE_API_KEY}
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    env_file:
      - ./.env
    networks:
      - app-network

  llama3:
    build: ./llama3
    ports:
      - "${LLAMA3_PORT}:${LLAMA3_PORT}"
    env_file:
      - ./.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
